# .github/actions/build-and-push-docker-image.yml
name: 'Build and Push Docker Image'
description: 'Builds a Docker image and pushes it to a registry'

inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        if [ "${runner.os}" == "Linux" ]; then
          # Use Bash commands for Linux
          docker build -t alikhan0/flask-app .
          docker push alikhan0/flask-app
          shell: bash
       else
         # Use PowerShell commands for Windows
         docker build -t alikhan0/flask-app .
         docker push alikhan0/flask-app
         shell: powershell
       fi

