# .github/actions/build-and-push-docker-image.yml
name: 'Installing Dependencies'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

   - name: Installing Dependencies
     run: |          
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       pip install -r test-requirements.txt
