# .github/actions/build-and-push-docker-image.yml
name: 'Installing Dependencies'

runs:
  using: 'composite'
  steps:
  - name: Checkout Repository
    uses: actions/checkout@v2

  - name: Installing Dependencies
    run: |          
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r test-requirements.txt
